# Key bindings for taking screenshots
#
# The image files will be written to XDG_SCREENSHOTS_DIR if this is set
# or defined in user-dirs.dir, or to a fallback location XDG_PICTURES_DIR.
#
# Copy the file to ~/.config/sway/config.d/60-bindings-screenshot.conf (or to
# your $XDG_CONFIG_HOME location if set differently) to be able to overwrite
# existing shortcuts.
# Check 'man grimshot' for additional commands that you may find useful.
#
# Requires:     grimshot

# set $brightness_notification_cmd  command -v notify-send >/dev/null && \
#         VALUE=$(light) && VALUE=${VALUE%%.*} && \
#         notify-send -e -h string:x-canonical-private-synchronous:brightness \
#             -h "int:value:$VALUE" -t 800 "Brightness: ${VALUE}%"
#
# bindsym XF86MonBrightnessDown exec 'STEP="$brightness_step" && light -U ${STEP:-5} && $brightness_notification_cmd'
# bindsym XF86MonBrightnessUp exec 'STEP="$brightness_step" && light -A ${STEP:-5} && $brightness_notification_cmd'


set $screenshots_dir  ${XDG_SCREENSHOTS_DIR:-${XDG_PICTURES_DIR:-$HOME/Pictures}}
set $screenshot_notification_cmd  command -v notify-send >/dev/null && \
        notify-send -t 800 "Screenshot saved " "$screenshots_dir"



bindsym {
    # Capture the currently active output
    Print       exec grimshot save output && $screenshot_notification_cmd
    # Capture the currently active window
    Shift+Print   exec grimshot save active && $screenshot_notification_cmd
    # Select and capture a custom rectangular area
    Ctrl+Print  exec grimshot save area && $screenshot_notification_cmd
}

# if the keyboard hasn't the print key i use this
bindsym {
    # Capture the currently active output
    $mod+p       exec grimshot save output && $screenshot_notification_cmd
    # Capture the currently active window
    $mod+Shift+p   exec grimshot save active && $screenshot_notification_cmd
    # Select and capture a custom rectangular area
    $mod+Ctrl+p  exec grimshot save area && $screenshot_notification_cmd
}
