require("kanopo.packer")
require("kanopo.impatient")
require("kanopo.nvim-tree")

require("kanopo.lsp")
require("kanopo.cmp")
require("kanopo.treesitter")
require("kanopo.null-ls")
require("kanopo.telescope")
require("kanopo.bufferline")
require("kanopo.gitsigns")
require("kanopo.todo-comments")
require("kanopo.fidget")
require("kanopo.comment")
require("kanopo.alpha")
require("kanopo.ccc")
require("kanopo.comment")

require("kanopo.lualine")
require("kanopo.theme")
require("kanopo.options")
require("kanopo.keymaps")
