require('kanopo.plugins.packer')

require('kanopo.plugins.impatient')
require('kanopo.plugins.gruvbox')
require('kanopo.plugins.tree-sitter')
require('kanopo.plugins.lualine')
require('kanopo.plugins.nvim-tree')
require('kanopo.plugins.lsp')
require('kanopo.plugins.glow')
require('kanopo.plugins.ccc')
require('kanopo.plugins.bufferline')
require('kanopo.plugins.telescope')
require('kanopo.plugins.autopairs')
require('kanopo.plugins.gitsigns')

require('kanopo.core.options')
require('kanopo.core.keymaps')
