
require("kanopo.plugins_setup.lualine")
require("kanopo.plugins_setup.nvim-tree")
require("kanopo.plugins_setup.treesitter")
require("kanopo.plugins_setup.which-key")
require("kanopo.plugins_setup.lsp")
require("kanopo.plugins_setup.cmp")
require("kanopo.plugins_setup.null-ls")
require("kanopo.plugins_setup.alpha")
require("kanopo.plugins_setup.dressing")
